packages:
  - apps/*
  - packages/*

injectWorkspacePackages: true

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@swc/core'
  - esbuild
  - msw
  - sharp
  - unrs-resolver

syncInjectedDepsAfterScripts:
  - build
  - test
