import type { Metadata } from "next";
import { Cabin } from "next/font/google";
import "./globals.css";
import NavigationBar from "@/components/NavigationBar";

const cabin = Cabin({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${cabin.className} antialiased`}>
        <main className="pt-16">
          <NavigationBar />
          {children}
        </main>
      </body>
    </html>
  );
}