import type { Metadata } from "next";
import { Cabin } from "next/font/google";
import "./globals.css";
import NavigationBar from "@/components/navigation/NavigationBar";
import { Auth0Provider } from "@auth0/nextjs-auth0";
import CartInitializer from "@/components/cart/CartInitializer";

const cabin = Cabin({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Atelier",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${cabin.className} antialiased`}>
        <Auth0Provider>
          <main className="pt-16">
            <CartInitializer />
            <NavigationBar />
            {children}
          </main>
        </Auth0Provider>
      </body>
    </html>
  );
}